'use server';
/**
 * @fileOverview A Genkit flow for generating background music with optional genre and mood refinements.
 *
 * - generateMusicWithGenreAndMood - A function that orchestrates the music generation process.
 * - GenerateMusicWithGenreAndMoodInput - The input type for the generateMusicWithGenreAndMood function.
 * - GenerateMusicWithGenreAndMoodOutput - The return type for the generateMusicWithGenreAndMood function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const GenerateMusicWithGenreAndMoodInputSchema = z.object({
  prompt: z.string().describe('A descriptive text prompt for the music generation.'),
  genre: z.enum(['Cinematic', 'Gaming', 'Lo-Fi', 'Electronic', 'Classical', 'Rock', 'Jazz']).optional().describe('An optional genre to guide the music style.'),
  mood: z.enum(['Happy', 'Sad', 'Energetic', 'Relaxing', 'Intense', 'Peaceful']).optional().describe('An optional mood to convey in the music.'),
  duration: z.number().optional().describe('Optional duration of the music in seconds. Defaults to 15 if not provided.'),
});
export type GenerateMusicWithGenreAndMoodInput = z.infer<typeof GenerateMusicWithGenreAndMoodInputSchema>;

const GenerateMusicWithGenreAndMoodOutputSchema = z.object({
  audioDataUri: z.string().describe(
    "The generated music as a data URI that must include a MIME type (e.g., 'audio/mp3' or 'audio/wav') and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
  ),
});
export type GenerateMusicWithGenreAndMoodOutput = z.infer<typeof GenerateMusicWithGenreAndMoodOutputSchema>;

// IMPORTANT: This tool is a placeholder. In a real application, it would interact with
// the FastAPI backend (as described in the blueprint) to trigger MusicGen and retrieve
// the generated audio. The FastAPI backend would need to be enhanced to return the
// audio as a base64 encoded data URI or a direct download URL.
const callMusicGenBackend = ai.defineTool(
  {
    name: 'callMusicGenBackend',
    description: 'Calls the external FastAPI backend to generate music using MusicGen based on a text prompt and returns the audio as a data URI.',
    inputSchema: z.object({
      combinedPrompt: z.string().describe('The full prompt to send to the MusicGen AI model.'),
      duration: z.number().optional().describe('The desired duration of the generated music in seconds. Defaults to 15.'),
    }),
    outputSchema: z.object({
      audioDataUri: z.string().describe(
        "The generated music as a data URI (e.g., 'data:audio/mp3;base64,<encoded_data>')"
      ),
    }),
  },
  async (input) => {
    console.log(`Simulating call to MusicGen backend with prompt: "${input.combinedPrompt}" and duration: ${input.duration || 15}s`);

    // Simulate a base64 encoded empty MP3 audio for demonstration purposes.
    // In a production environment, you would make an actual HTTP request here.
    // This is a minimal valid MP3 file (1 frame, silence) for demonstration, identical to generateMusicFromPrompt
    const simulatedMp3Base64 = "SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2YzU4LjY2LjEwMAAAAAAAAAAAAAAA//tQwAAAAAAIAAAAAAAAAAHgAAAAAAAAAA//tQwgAAAQIxAAAAAAAAAAADSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMQADSAxhuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMQEDSAxhuAAAAAAAAAAAIDhCUABDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMQGAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYGBAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYgDB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYkDw0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYoERA1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYsFhQ1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYwGxU1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMY4HRc1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMY8IRg1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZAJh01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZCKSY1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZELCc1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZgMTY1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZmNjk1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZsPz81AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZ0RQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZ4SUsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZ8UlMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaAUU8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaCUloAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaCU0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaIUmgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaQVGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaUWGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaYV2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMacXGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMagYmIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMakZWUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaoaWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMawcGcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMa0dGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMa4fWoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMa8h3IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbAgIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbEY6wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbQj8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbUksAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbYl9kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbaG1oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbeIHYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbgj3gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbhM4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbmU/oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMboWGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbwW7wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMb0c68AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMb4eK4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMb8fP0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMb+j/UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMcADuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMcAEyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMcAGmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMcAIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMcALAAAAAAAAAAAAAAA";

    return { audioDataUri: `data:audio/mp3;base64,${simulatedMp3Base64}` };
  }
);

export const generateMusicWithGenreAndMood = ai.defineFlow(
  {
    name: 'generateMusicWithGenreAndMood',
    inputSchema: GenerateMusicWithGenreAndMoodInputSchema,
    outputSchema: GenerateMusicWithGenreAndMoodOutputSchema,
  },
  async (input: GenerateMusicWithGenreAndMoodInput) => {
    // Combine prompt, genre, and mood for the model
    const promptParts = [input.prompt];
    if (input.genre) promptParts.push(`Genre: ${input.genre}`);
    if (input.mood) promptParts.push(`Mood: ${input.mood}`);
    const combinedPrompt = promptParts.join(', ').trim();

    try {
      const result = await callMusicGenBackend({
        combinedPrompt,
        duration: input.duration,
      });
      return { audioDataUri: result.audioDataUri };
    } catch (error: any) {
      console.error('Error generating music with genre and mood:', error);
      throw new Error(`Music generation failed: ${error.message}`);
    }
  }
);
