'use server';
/**
 * @fileOverview A Genkit flow for generating background music from a text prompt.
 * This flow encapsulates the interaction with an external MusicGen AI service
 * (conceptualized as a tool) to produce an audio composition.
 *
 * - generateMusicFromPrompt - A function that handles the music generation process.
 * - GenerateMusicFromPromptInput - The input type for the generateMusicFromPrompt function.
 * - GenerateMusicFromPromptOutput - The return type for the generateMusicFromPrompt function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

/**
 * Input schema for the music generation flow.
 */
const GenerateMusicFromPromptInputSchema = z.object({
  prompt: z.string().describe('A descriptive text prompt for the music to be generated (e.g., "cinematic emotional background music").'),
  durationSeconds: z.number().int().min(5).max(60).default(15).describe('The desired duration of the music in seconds, between 5 and 60.'),
  genre: z.string().optional().describe('Optional genre preference (e.g., "Cinematic", "Lo-Fi").'),
  mood: z.string().optional().describe('Optional mood preference (e.g., "happy", "sad", "energetic").'),
});
export type GenerateMusicFromPromptInput = z.infer<typeof GenerateMusicFromPromptInputSchema>;

/**
 * Output schema for the music generation flow.
 */
const GenerateMusicFromPromptOutputSchema = z.object({
  audioDataUri: z.string().describe('The generated music as a Base64 encoded audio data URI (e.g., "data:audio/mp3;base64,...").'),
});
export type GenerateMusicFromPromptOutput = z.infer<typeof GenerateMusicFromPromptOutputSchema>;

/**
 * Genkit tool that simulates calling an external MusicGen AI service via a FastAPI backend.
 * In a real application, this tool would make an HTTP request to the FastAPI endpoint
 * and retrieve the generated audio data.
 */
const generateMusicTool = ai.defineTool(
  {
    name: 'generateMusicWithMusicGen',
    description: 'Generates an original music composition based on a text prompt and duration using an external MusicGen AI service.',
    inputSchema: GenerateMusicFromPromptInputSchema,
    outputSchema: GenerateMusicFromPromptOutputSchema,
  },
  async (input) => {
    // --- SIMULATED EXTERNAL API CALL ---
    // In a production environment, this would involve an actual HTTP call to the FastAPI backend:
    // const response = await fetch(`http://localhost:8000/generate?prompt=${encodeURIComponent(input.prompt)}&duration=${input.durationSeconds}`);
    // const data = await response.json();
    // The FastAPI backend would need to return the audio data URI directly or provide a mechanism to fetch it.
    console.log(`Simulating call to MusicGen service with prompt: "${input.prompt}", duration: ${input.durationSeconds}s, genre: ${input.genre || 'N/A'}, mood: ${input.mood || 'N/A'}`);

    // Mock audio data URI (a small, silent MP3 base64 string).
    // This is a placeholder; a real implementation would return actual generated audio.
    const mockAudioBase64 = "SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2YzU4LjY2LjEwMAAAAAAAAAAAAAAA//tQwAAAAAAIAAAAAAAAAAHgAAAAAAAAAA//tQwgAAAQIxAAAAAAAAAAADSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMQADSAxhuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMQEDSAxhuAAAAAAAAAAAIDhCUABDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMQGAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYGBAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYgDB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYkDw0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYoERA1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYsFhQ1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMYwGxU1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMY4HRc1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMY8IRg1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZAJh01AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZCKSY1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZELCc1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZgMTY1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZmNjk1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZsPz81AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZ0RQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZ4SUsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMZ8UlMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaAUU8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaCUloAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaCU0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaIUmgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaQVGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaUWGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaYV2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMacXGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMagYmIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMakZWUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMaoaWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMawcGcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMa0dGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMa4fWoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMa8h3IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbAgIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbEY6wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbQj8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbUksAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbYl9kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbaG1oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbeIHYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbgj3gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbhM4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbmU/oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMboWGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMbwW7wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMb0c68AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMb4eK4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMb8fP0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMb+j/UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMcADuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMcAEyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMcAGmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMcAIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7UMcALAAAAAAAAAAAAAAA";
    const audioDataUri = `data:audio/mp3;base64,${mockAudioBase64}`;

    return { audioDataUri };
  }
);

/**
 * Genkit flow for generating background music. It directly calls the `generateMusicTool`.
 */
const generateMusicFromPromptFlow = ai.defineFlow(
  {
    name: 'generateMusicFromPromptFlow',
    inputSchema: GenerateMusicFromPromptInputSchema,
    outputSchema: GenerateMusicFromPromptOutputSchema,
  },
  async (input) => {
    // The flow directly invokes the music generation tool with the provided input.
    const result = await generateMusicTool(input);
    return result;
  }
);

/**
 * Wrapper function to execute the `generateMusicFromPromptFlow`.
 * @param input - The input for the music generation, including prompt and duration.
 * @returns The generated music as an audio data URI.
 */
export async function generateMusicFromPrompt(input: GenerateMusicFromPromptInput): Promise<GenerateMusicFromPromptOutput> {
  return generateMusicFromPromptFlow(input);
}
